### ISSUE TITLE
Подключение статики

### ISSUE THREAD

**Issue by v-bekh** [ArthurShakirov125/PracticePhP#1]
https://github.com/ArthurShakirov125/PracticePhP/blob/dbbb58cad351436cf9fadc56b92a2bd09411d3ba/classes/Layout.php#L50

А если файла не существует? А если один и тот же подключу раз 15?

**Comment by ArthurShakirov125** [comment]
Исправил. Добавил проверку существует ли файл. Массивы проверил на повторение
