### ISSUE TITLE
Странность

### ISSUE THREAD

**Issue by v-bekh** [ArthurShakirov125/PracticePhP#6]
https://github.com/ArthurShakirov125/PracticePhP/blob/ccd2d500a79f34d3f1d3ae779a06dd215eca97d3/classes/db.php#L90

Почему именно тут идет другое условие?

**Comment by ArthurShakirov125** [comment]
Потому что MySQL требует чтобы у varchar была определена длинна, если просто присвоить varchar будет ошибка
