### ISSUE TITLE
Прямая запись

### ISSUE THREAD

**Issue by v-bekh** [ArthurShakirov125/PracticePhP#7]
https://github.com/ArthurShakirov125/PracticePhP/blob/7b7ab038db56359ed1d6e9cc3bcb45744f1fcfe4/classes/Model.php#L65

Не очень хорошо писать значения из БД напрямую во внутреннее свойство. А если перед записью значения потребуется сделать какой то обработчик? Например привести timestamp в нужный строковый формат и т.д.

**Comment by v-bekh** [comment]
find то же самое

**Comment by v-bekh** [comment]
Да и в целом посмотри, весь класс так работает, напрямую со свойством

**Comment by ArthurShakirov125** [comment]
Добавил метод set_entry() чтобы не обращаться на прямую к свойству, в нём и доп логику прописать можно будет
