### ISSUE TITLE
Необязательные ключи

### ISSUE THREAD

**Issue by v-bekh** [ArthurShakirov125/PracticePhP#8]
https://github.com/ArthurShakirov125/PracticePhP/blob/7b7ab038db56359ed1d6e9cc3bcb45744f1fcfe4/classes/product.php#L8

Навреное не очень удобно каждый раз отмечать primary или нет? Разработчику тоже будет лень заполнять везде

**Comment by ArthurShakirov125** [comment]
Исправил.
